/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./Mocks";
export type { mocks };
import type * as paradoxSol from "./Paradox.sol";
export type { paradoxSol };
import type * as parapad from "./Parapad";
export type { parapad };
import type * as stakePoolSol from "./StakePool.sol";
export type { stakePoolSol };
export type { Lock } from "./Lock";
export type { ParadoxTimelock } from "./ParadoxTimelock";
export type { ParadoxToken } from "./ParadoxToken";
export type { Utilities } from "./Utilities";
