/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPARA__factory } from "./IPARA__factory";
export { StakePool__factory } from "./StakePool__factory";
