/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPARA,
  IPARAInterface,
} from "../../../contracts/StakePool.sol/IPARA";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPARA__factory {
  static readonly abi = _abi;
  static createInterface(): IPARAInterface {
    return new utils.Interface(_abi) as IPARAInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IPARA {
    return new Contract(address, _abi, signerOrProvider) as IPARA;
  }
}
